import { exhibitManifestSchema, type ExhibitManifest } from "@/lib/exhibit-schema";

/**
 * The built-in exhibits are synthetic, deterministic judge fixtures. They exercise
 * two different interaction mechanics without presenting generated material as a
 * real family's history.
 */
export const nightMarketExhibit: ExhibitManifest = exhibitManifestSchema.parse({
  schemaVersion: "1.0",
  id: "exhibit-night-market-1998",
  slug: "lantern-lane-1998",
  title: "Lantern Lane, 1998",
  subtitle: "Collect the three lantern details preserved in one summer photograph.",
  dedication: "For every ordinary evening that became family folklore.",
  truthNote:
    "Built-in demonstration made from synthetic source material. Facts are linked to the illustrated source photograph, timestamped demo narration, or an explicit demo confirmation; atmospheric scenery is interpretation.",
  palette: {
    ink: "#27150f",
    paper: "#fff1cf",
    accent: "#df4b2f",
    glow: "#ffc85c",
  },
  sources: [
    {
      id: "night-photo-left-lantern",
      kind: "photo",
      label: "Source photograph · left lantern",
      assetPath: "/samples/night-market-source.svg",
      capturedAt: "1998-08",
      region: { x: 0.05, y: 0.08, width: 0.25, height: 0.48 },
    },
    {
      id: "night-photo-center-lantern",
      kind: "photo",
      label: "Source photograph · center lantern",
      assetPath: "/samples/night-market-source.svg",
      capturedAt: "1998-08",
      region: { x: 0.36, y: 0.05, width: 0.26, height: 0.5 },
    },
    {
      id: "night-photo-right-lantern",
      kind: "photo",
      label: "Source photograph · right lantern",
      assetPath: "/samples/night-market-source.svg",
      capturedAt: "1998-08",
      region: { x: 0.68, y: 0.1, width: 0.25, height: 0.46 },
    },
    {
      id: "night-audio-lantern",
      kind: "audio",
      label: "Synthetic demo narration · lanterns",
      assetPath: "/samples/night-market-voice.m4a",
      timeStartSeconds: 0,
      timeEndSeconds: 5.28,
      excerpt: "Three lanterns hung over the lane: one painted, one tasseled, one pale as moonlight.",
    },
    {
      id: "night-audio-ticket",
      kind: "audio",
      label: "Synthetic demo narration · paper ticket",
      assetPath: "/samples/night-market-voice.m4a",
      timeStartSeconds: 5.53,
      timeEndSeconds: 8.62,
      excerpt: "I kept the red paper ticket tucked behind the photograph.",
    },
    {
      id: "night-audio-bell",
      kind: "audio",
      label: "Synthetic demo narration · bicycle bell",
      assetPath: "/samples/night-market-voice.m4a",
      timeStartSeconds: 8.87,
      timeEndSeconds: 11.61,
      excerpt: "A bicycle bell rang as we reached the last lantern.",
    },
    {
      id: "night-human-date",
      kind: "human",
      label: "Demo storyteller confirmation",
      capturedAt: "1998-08",
      excerpt: "For this fictional demo, the storyteller confirms the envelope was marked August 1998.",
    },
  ],
  claims: [
    {
      id: "claim-night-date",
      text: "The source envelope is marked August 1998.",
      status: "human-confirmed",
      sourceIds: ["night-human-date"],
    },
    {
      id: "claim-left-lantern",
      text: "A painted lantern appears at the left edge of the source photograph.",
      status: "source-backed",
      sourceIds: ["night-photo-left-lantern", "night-audio-lantern"],
    },
    {
      id: "claim-center-lantern",
      text: "A tasseled lantern appears above the center of the lane.",
      status: "source-backed",
      sourceIds: ["night-photo-center-lantern", "night-audio-lantern"],
    },
    {
      id: "claim-right-lantern",
      text: "A pale lantern appears on the right side of the photograph.",
      status: "source-backed",
      sourceIds: ["night-photo-right-lantern", "night-audio-lantern"],
    },
    {
      id: "claim-paper-ticket",
      text: "The storyteller says a red paper ticket was kept with the photograph.",
      status: "source-backed",
      sourceIds: ["night-audio-ticket"],
    },
    {
      id: "claim-bicycle-bell",
      text: "The storyteller remembers a bicycle bell near the last lantern.",
      status: "source-backed",
      sourceIds: ["night-audio-bell"],
    },
    {
      id: "claim-bicycle-owner",
      text: "The bicycle belonged to someone in the storyteller's family.",
      status: "uncertain",
      sourceIds: ["night-audio-bell"],
    },
  ],
  scenes: [
    {
      id: "scene-lantern-lane",
      title: "Find the light that survived the photograph",
      eyebrow: "August 1998 · source-grounded demo",
      narration:
        "The illustrated lane is an interpretation arranged around five verifiable details. Collect the three lanterns in any order; the ticket and bell open additional source cards.",
      stage: "lantern-lane",
      sourceIds: [
        "night-photo-left-lantern",
        "night-photo-center-lantern",
        "night-photo-right-lantern",
        "night-audio-lantern",
        "night-audio-ticket",
        "night-audio-bell",
        "night-human-date",
      ],
      hotspots: [
        {
          id: "hotspot-painted-lantern",
          title: "The painted lantern",
          shortLabel: "Painted",
          body: "Its painted bands are visible in the left photo region and named in the opening narration.",
          xPercent: 18,
          yPercent: 27,
          scale: 1.08,
          icon: "lantern",
          claimIds: ["claim-left-lantern", "claim-night-date"],
          sourceIds: ["night-photo-left-lantern", "night-audio-lantern", "night-human-date"],
          interpretation: "The surrounding awning and glow are generated atmosphere, not documentary fact.",
        },
        {
          id: "hotspot-tasseled-lantern",
          title: "The tasseled lantern",
          shortLabel: "Tasseled",
          body: "The center photograph crop preserves its long tassel; the synthetic narration describes the same detail.",
          xPercent: 49,
          yPercent: 20,
          scale: 1.22,
          icon: "lantern",
          claimIds: ["claim-center-lantern"],
          sourceIds: ["night-photo-center-lantern", "night-audio-lantern"],
          interpretation: "The animated sway is an interpretive motion cue.",
        },
        {
          id: "hotspot-pale-lantern",
          title: "The pale lantern",
          shortLabel: "Pale",
          body: "A light-toned lantern occupies the right photo region and closes the three-lantern recollection.",
          xPercent: 79,
          yPercent: 31,
          scale: 0.96,
          icon: "lantern",
          claimIds: ["claim-right-lantern"],
          sourceIds: ["night-photo-right-lantern", "night-audio-lantern"],
          interpretation: "The moonlike bloom is generated scenery.",
        },
        {
          id: "hotspot-paper-ticket",
          title: "The paper ticket",
          shortLabel: "Ticket",
          body: "This detail comes from the 00:05.53–00:08.62 transcript excerpt rather than the photograph.",
          xPercent: 34,
          yPercent: 78,
          scale: 0.82,
          icon: "ticket",
          claimIds: ["claim-paper-ticket"],
          sourceIds: ["night-audio-ticket"],
          interpretation: "Its position on the lane is interpretive; only the spoken memory is asserted.",
        },
        {
          id: "hotspot-bicycle-bell",
          title: "A bell at the edge",
          shortLabel: "Bell",
          body: "The final transcript excerpt remembers a bicycle bell, without identifying its rider.",
          xPercent: 88,
          yPercent: 76,
          scale: 0.78,
          icon: "bell",
          claimIds: ["claim-bicycle-bell", "claim-bicycle-owner"],
          sourceIds: ["night-audio-bell"],
          interpretation: "The visible bicycle silhouette is an interpretive marker, not a claimed likeness.",
        },
      ],
      interaction: {
        kind: "collect",
        prompt: "Collect the three lanterns preserved by the source photograph.",
        targetHotspotIds: ["hotspot-painted-lantern", "hotspot-tasseled-lantern", "hotspot-pale-lantern"],
        completionMessage: "Three lights, three citations. The lane is complete without adding a new fact.",
      },
    },
  ],
  buildEvidence: {
    model: "GPT-5.6 blueprint contract + Codex live verification",
    agents: [
      {
        name: "Story cartographer",
        role: "Mapped each remembered detail to a photo region or transcript range.",
        result: "Five source-linked details, one confirmed date, and one visible uncertainty.",
        status: "reviewed",
      },
      {
        name: "Interaction builder",
        role: "Selected a non-linear collection mechanic for the three visual anchors.",
        result: "Collect interaction compiled to the typed exhibit runtime.",
        status: "passed",
      },
      {
        name: "Truth auditor",
        role: "Checked references and labeled generated atmosphere.",
        result: "No orphaned claims or unlabeled interpretive hotspot copy.",
        status: "passed",
      },
    ],
    tests: [
      { name: "Manifest schema", detail: "All claim, source, hotspot, and interaction references resolve.", status: "passed" },
      { name: "Collect mechanic", detail: "The three lantern targets are distinct and order-independent.", status: "passed" },
    ],
    generatedFiles: ["src/lib/sample-exhibits.ts", "docs/evidence/codex-live-run.json"],
  },
});

export const bicycleRepairExhibit: ExhibitManifest = exhibitManifestSchema.parse({
  schemaVersion: "1.0",
  id: "exhibit-bicycle-repair",
  slug: "four-moves-at-the-repair-bench",
  title: "Four Moves at the Repair Bench",
  subtitle: "Rebuild a remembered bicycle ritual in the order the storyteller taught it.",
  dedication: "For the hands that taught by doing.",
  truthNote:
    "Built-in demonstration made from synthetic source material. The repair order is grounded in timestamped demo narration and illustrated photo regions. Bench scenery and motion are labeled interpretation.",
  palette: {
    ink: "#132821",
    paper: "#f2eedf",
    accent: "#df6b35",
    glow: "#b8db90",
  },
  sources: [
    {
      id: "repair-photo-bicycle",
      kind: "photo",
      label: "Source photograph · bicycle frame",
      assetPath: "/samples/repair-bench-source.svg",
      region: { x: 0.06, y: 0.12, width: 0.62, height: 0.75 },
    },
    {
      id: "repair-photo-wrench",
      kind: "photo",
      label: "Source photograph · small wrench",
      assetPath: "/samples/repair-bench-source.svg",
      region: { x: 0.65, y: 0.5, width: 0.24, height: 0.22 },
    },
    {
      id: "repair-photo-bell",
      kind: "photo",
      label: "Source photograph · handlebar bell",
      assetPath: "/samples/repair-bench-source.svg",
      region: { x: 0.48, y: 0.08, width: 0.2, height: 0.2 },
    },
    {
      id: "repair-audio-tire",
      kind: "audio",
      label: "Synthetic demo narration · tire first",
      assetPath: "/samples/repair-bench-voice.m4a",
      timeStartSeconds: 0,
      timeEndSeconds: 3.96,
      excerpt: "First turn the bicycle over and let the seat and handlebars hold it steady.",
    },
    {
      id: "repair-audio-bolt",
      kind: "audio",
      label: "Synthetic demo narration · loosen the wheel",
      assetPath: "/samples/repair-bench-voice.m4a",
      timeStartSeconds: 4.21,
      timeEndSeconds: 6.53,
      excerpt: "Next use the small wrench to loosen the wheel.",
    },
    {
      id: "repair-audio-chain-bell",
      kind: "audio",
      label: "Synthetic demo narration · chain then bell",
      assetPath: "/samples/repair-bench-voice.m4a",
      timeStartSeconds: 6.78,
      timeEndSeconds: 11.36,
      excerpt: "Set the chain back on its teeth, spin the wheel, and ring the bell when it runs clean.",
    },
  ],
  claims: [
    {
      id: "claim-repair-bike-first",
      text: "The demonstration begins by turning the bicycle over.",
      status: "source-backed",
      sourceIds: ["repair-photo-bicycle", "repair-audio-tire"],
    },
    {
      id: "claim-repair-wrench-second",
      text: "The small wrench is used to loosen the wheel next.",
      status: "source-backed",
      sourceIds: ["repair-photo-wrench", "repair-audio-bolt"],
    },
    {
      id: "claim-repair-chain-third",
      text: "The chain is returned to its teeth before the wheel is tested.",
      status: "source-backed",
      sourceIds: ["repair-audio-chain-bell"],
    },
    {
      id: "claim-repair-bell-last",
      text: "The remembered ritual ends by ringing the handlebar bell after the wheel runs clean.",
      status: "source-backed",
      sourceIds: ["repair-photo-bell", "repair-audio-chain-bell"],
    },
  ],
  scenes: [
    {
      id: "scene-repair-bench",
      title: "Put the ritual back in order",
      eyebrow: "Four steps · three evidence ranges",
      narration:
        "The bench layout is an interpretation. Select the four source-backed actions in the order spoken by the storyteller; a wrong step resets the sequence.",
      stage: "repair-bench",
      sourceIds: [
        "repair-photo-bicycle",
        "repair-photo-wrench",
        "repair-photo-bell",
        "repair-audio-tire",
        "repair-audio-bolt",
        "repair-audio-chain-bell",
      ],
      hotspots: [
        {
          id: "hotspot-turn-bike",
          title: "Turn the bicycle over",
          shortLabel: "Turn",
          body: "The opening transcript range and bicycle photo establish the first move.",
          xPercent: 30,
          yPercent: 54,
          scale: 1.15,
          icon: "bicycle",
          claimIds: ["claim-repair-bike-first"],
          sourceIds: ["repair-photo-bicycle", "repair-audio-tire"],
          interpretation: "The flip animation visualizes the instruction; it is not archival footage.",
        },
        {
          id: "hotspot-loosen-wheel",
          title: "Loosen the wheel",
          shortLabel: "Loosen",
          body: "The small wrench in the photograph supports the second spoken action.",
          xPercent: 72,
          yPercent: 66,
          scale: 0.9,
          icon: "wrench",
          claimIds: ["claim-repair-wrench-second"],
          sourceIds: ["repair-photo-wrench", "repair-audio-bolt"],
          interpretation: "The spark at the wrench is a generated interaction cue.",
        },
        {
          id: "hotspot-seat-chain",
          title: "Seat the chain",
          shortLabel: "Chain",
          body: "The 00:06.78–00:11.36 excerpt places the chain before the final test.",
          xPercent: 51,
          yPercent: 72,
          scale: 0.82,
          icon: "note",
          claimIds: ["claim-repair-chain-third"],
          sourceIds: ["repair-audio-chain-bell"],
          interpretation: "The highlighted chain path is an explanatory overlay.",
        },
        {
          id: "hotspot-ring-bell",
          title: "Ring the bell",
          shortLabel: "Ring",
          body: "The bell is visible in the photograph and named as the closing action in the narration.",
          xPercent: 58,
          yPercent: 28,
          scale: 0.78,
          icon: "bell",
          claimIds: ["claim-repair-bell-last"],
          sourceIds: ["repair-photo-bell", "repair-audio-chain-bell"],
          interpretation: "The expanding sound rings are generated feedback.",
        },
      ],
      interaction: {
        kind: "sequence",
        prompt: "Replay the four repair moves in the storyteller's order.",
        stepHotspotIds: ["hotspot-turn-bike", "hotspot-loosen-wheel", "hotspot-seat-chain", "hotspot-ring-bell"],
        successMessage: "The wheel turns clean. One practical memory has become something you can perform.",
        retryMessage: "That move came later in the story. The bench resets so you can follow the evidence again.",
      },
    },
  ],
  buildEvidence: {
    model: "GPT-5.6 blueprint contract + Codex typed-runtime build",
    agents: [
      {
        name: "Story cartographer",
        role: "Converted timestamped instructions into an ordered evidence graph.",
        result: "Four actions mapped to three narration ranges and three photo regions.",
        status: "reviewed",
      },
      {
        name: "Interaction builder",
        role: "Compiled the evidence graph into a reset-on-error sequence.",
        result: "Four-step sequence interaction generated for the typed runtime.",
        status: "passed",
      },
      {
        name: "Truth auditor",
        role: "Checked step order and separated overlays from factual claims.",
        result: "Every action resolves to at least one transcript or photo source.",
        status: "passed",
      },
    ],
    tests: [
      { name: "Manifest schema", detail: "All claim, source, hotspot, and interaction references resolve.", status: "passed" },
      { name: "Sequence mechanic", detail: "The ordered path has four distinct, source-backed steps.", status: "passed" },
    ],
    generatedFiles: ["src/lib/sample-exhibits.ts"],
  },
});

export const sampleExhibits: ExhibitManifest[] = [nightMarketExhibit, bicycleRepairExhibit];

export function getSampleExhibit(slug = nightMarketExhibit.slug): ExhibitManifest {
  const selected = sampleExhibits.find((exhibit) => exhibit.slug === slug) ?? nightMarketExhibit;
  return structuredClone(selected);
}
